#!/bin/bash

#get access to the variables from .auth file
export IMAGE=$(sed -n '1p' /tmp/.auth)
export TAG=$(sed -n '2p' /tmp/.auth)
export PASS=$(sed -n '3p' /tmp/.auth)

#login to the dockerhub using id and password
docker login -u ricardoandre97 -p $PASS
#cd to the maven folder and run the image which is crested inside remote machine
cd ~/maven && docker-compose up -d
